app/api/urls.py
import os
import environ
from django.contrib import admin
from django.urls import re_path
from .views_authentication import *
env = environ.Env()
environ.Env.read_env()

admin.autodiscover()
app_name = 'api'


urlpatterns = [
    ## Authentication
    # re_path(r'^user-signup-api/$',UserSignupView.as_view(),name="user_signup_api"),
    re_path(r'^user-login-api/$',UserLoginView.as_view(),name="user_login_api"),
    re_path(r'^check-user-api/$', UserCheckView.as_view(), name='check_user_api'),
    re_path(r'^delete-account-api/$',DeleteAccount.as_view(),name="delete_account_api"),
    re_path(r'^deactivate-account-api/$',DeactivateAccount.as_view(),name="deactivate_account_api"),
    re_path(r'^logout-api/$', LogoutView.as_view(), name='logout_api'),

    re_path(r'^verify-otp-api/$',VerifyOTP.as_view(),name="verify_otp_api"),
    re_path(r'^resend-otp-api/$',ResendOTP.as_view(),name="resend_otp_api"),

    re_path(r'^check-user-mail/$',CheckUserEmail.as_view(),name="check_user_mail"),
    
    re_path(r'^forgot-password-api/$',ForgotPassword.as_view(),name="forgot_password_api"),
    re_path(r'^forgot-password-resend-otp/$',ForgotPasswordResendOTP.as_view(),name="forgot_password_resend_otp_api"),
    
    ##Security Management
    re_path(r'^change-password-api/$',ChangePassword.as_view(),name="change_password_api"),
    re_path(r'^reset-password/$',ResetPasswordView.as_view(),name="reset_password_api"),

    ## Profile Management
    re_path(r'^profile-details-api/$',UserProfileDetails.as_view(),name="user_profile_details_api"),
    re_path(r'^update-profile-api/$',UpdateProfileDetails.as_view(),name="update_profile_api"),
    re_path(r'^update-mobile-number-api/$',UpdateMobileNumberView.as_view(),name="update_mobile_number_api"),
    re_path(r'^verify-mobile-number-api/$',VerifyMobileNumberView.as_view(),name="verify_mobile_number_api"),

    ## Static Pages
    re_path(r'^static-pages-api/$',StaticPages.as_view(),name="static_pages_api"),

    ## Faq Management
    re_path(r'^faq-list-api/$',FaqList.as_view(),name="faq_list_api"),
    
    ## Contact Us Management
    re_path(r'^contact-us-api/$',ContactUsView.as_view(),name="contact_us_api"),

    ## Notification Management
    re_path(r'^update-notification-settings-api/$',UpdateNotificationSettings.as_view(),name="update_notification_settings_api"),
    re_path(r'^notifications-list-api/$',NotificationsList.as_view(),name="notifications_list_api"),
    re_path(r'^clear-all-notifications-api/$',ClearAllNotifications.as_view(),name="clear_notifications_api"),
    re_path(r'^delete-notification-api/$',DeleteNotification.as_view(),name="delete_notification_api"),
    re_path(r'^mark-read-notification-api/$',MarkReadNotification.as_view(),name="mark_read_notification_api"),
    
]

app/project/urls.py
from django.contrib import admin
from frontend.views import *
from accounts.views import  *
from django.conf import settings
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import  AdminLoginView
from django.views.static import serve

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from drf_yasg.generators import OpenAPISchemaGenerator


class SchemaGenerator(OpenAPISchemaGenerator):
    def get_schema(self, request=None, public=False):
        schema = super(SchemaGenerator, self).get_schema(request, public)
        schema.basePath = os.path.join(schema.basePath, '')
        schema.schemes = ["http", "https"]
        return schema


schema_view = get_schema_view(
    openapi.Info(
        title = "<ProjectName>'s API's",
        description = "API documentation for <ProjectName> Project",
        default_version = "1.0.0",
        terms_of_service = env('BASE_URL')+"/terms-and-conditions/",
        contact = openapi.Contact(email=""),
        license = openapi.License(name="<ProjectName>"),
    ),
    public = True,
    permission_classes = (permissions.AllowAny,),
    generator_class = SchemaGenerator
)



urlpatterns = [
    re_path(r'^admin/login/', AdminLoginView.as_view()),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'',include('frontend.urls')),

    ## Documentation Swagger
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^documentation/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    re_path(r'^accounts/', include('accounts.urls',)),
    re_path(r'^api/', include('api.urls',)),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^logger/', include('logger.urls',)),
    re_path(r'^users/', include('users.urls',)),
    re_path(r'^static-pages/', include('static_pages.urls',)),
    re_path(r'^backup/', include('backup.urls',)),
    re_path(r'^contact-us/', include('contact_us.urls',)),
    re_path(r'^credentials/', include('credentials.urls',)),
    re_path(r'^sellers/', include('sellers.urls',)),
    re_path(r'^products/', include('products.urls',)),
    # re_path(r'^chat/', include('chat.urls',)),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.handler404'
handler500 = 'frontend.views.handler500'
handler403 = 'frontend.views.handler403'
handler400 = 'frontend.views.handler400'

app/sellers/urls.py
import os
import environ
from django.contrib import admin
from django.urls import re_path
from .views_api import *
from .views_api import *
from .views import *
env = environ.Env()
environ.Env.read_env()

admin.autodiscover()
app_name = 'sellers'

urlpatterns = [
    # Seller Management Admin Panel
    re_path(r'^seller-list/$', SellerList.as_view(), name='seller_list'),
    re_path(r'^seller-graph/$', SellersGraph.as_view(), name='seller_graph'),
]

app/users/urls.py
from .views import *
from django.contrib import admin
from django.urls import re_path
from .views_graphs import *
from .views_exports import *
admin.autodiscover()
app_name = 'users'


urlpatterns = [

    ## Users
    re_path(r'^view-profile/(?P<id>[-\w]+)/$',ViewUser.as_view(), name='view_user'),
    re_path(r'^edit-admin/(?P<id>[-\w]+)/$',EditAdmin.as_view(), name='edit_admin'),
    re_path(r'^customers-list/$', BuyersList.as_view(), name='customers_list'),
    re_path(r'^add-user/$', AddUser.as_view(), name='add_user'),
    re_path(r'^edit-user/(?P<id>[-\w]+)/$', EditUser.as_view(), name='edit_user'),

    ## User Actions
    re_path(r'^deactivate-user/(?P<id>[-\w]+)/$',InactivateUser.as_view(), name='inactivate_user'),
    re_path(r'^delete-user/(?P<id>[-\w]+)/$',DeleteUser.as_view(), name='delete_user'),
    re_path(r'^activate-user/(?P<id>[-\w]+)/$',ActivateUser.as_view(), name='activate_user'),

    ## Panel Graphs
    re_path(r'^user-graph/$', UserGraph.as_view(), name='users_graph'),
    # re_path(r'^revenue-graph/$',RevenueGraph.as_view(), name='revenue_graph'),
    re_path(r'^users-analytical-graph/$',UserAnalyticGraphdata.as_view(), name='users_analytical_graph'),

    ## Download
    re_path(r'^download-customer-reports/$',DownLoadBuyerReports.as_view(), name='download_customer_reports'),

    re_path(r'^revenue-graph-weekly/$', RevenueGraphWeekly.as_view(), name='revenue_graph_weekly'),
    re_path(r'^revenue-graph/$', RevenueGraph.as_view(), name='revenue_graph'),
    re_path(r'^booking-graph/$', TicketBookingGraph.as_view(), name='booking_graph'),
]

app/sellers/models.py
from django.db import models
from accounts.models import *

class PromoCodes(CommonInfo):
    name = models.CharField(max_length=255, null=True, blank=True)
    code = models.CharField(max_length=255, null=True, blank=True)
    status=models.BooleanField(default=True)
    discount = models.FloatField(default=0.0,null=True, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)

    class Meta:
        managed=True
        db_table = 'promo_codes'

app/users/models.py
from django.db import models

app/sellers/views.py
import calendar
from accounts.common_imports import *
from calendar import monthrange, month_name

class SellerList(View):
    @method_decorator(admin_only)
    def get(self, request, *args, **kwargs):
        users = User.objects.filter(role_id=SELLER).exclude(temp=True).order_by('-created_on').only('id')
        if request.GET.get('username'):
            users = users.filter(username__icontains = request.GET.get('username').strip())
        if request.GET.get('full_name'):
            users = users.filter(full_name__icontains = request.GET.get('full_name').strip())
        if request.GET.get('email'):
            users = users.filter(email__icontains = request.GET.get('email').strip())
        if request.GET.get('mobile_no'):
            users = users.filter(id__in=[i.id for i in users if request.GET.get('mobile_no').strip() in str(i.country_code)+str(i.mobile_no)])
        if request.GET.get('created_on_from'):
            users = users.filter(created_on__date__gte = request.GET.get('created_on_from'))
        if request.GET.get('created_on_to'):
            users = users.filter(created_on__date__lte = request.GET.get('created_on_to'))
        if request.GET.get('status'):
            users = users.filter(status=request.GET.get('status'))
        if request.GET and not users:
            messages.error(request, 'No Data Found!')
        return render(request,'users/sellers/sellers.html',{
            "head_title":'Sellers Management',
            "users" : get_pagination(request, users),
            "full_name":request.GET.get('full_name') if request.GET.get('full_name') else "",
            "username":request.GET.get('username') if request.GET.get('username') else "",
            "email":request.GET.get('email') if request.GET.get('email') else "",
            "mobile_no":request.GET.get('mobile_no') if request.GET.get('mobile_no') else "",
            "created_on_from":request.GET.get('created_on_from') if request.GET.get('created_on_from') else "",
            "created_on_to":request.GET.get('created_on_to') if request.GET.get('created_on_to') else "",
            "status":request.GET.get('status') if request.GET.get('status') else "",
            "scroll_required":True if request.GET else False,

        })
    

class SellersGraph(View):
    @method_decorator(admin_only)
    def get(self, request, *args, **kwargs):
        data = {"data":[],'Sellers_count':[],'active_Sellers_count':[],'inactive_Sellers_count':[],'deleted_Sellers_count':[],'month_name':[]}
        selected_year = request.GET.get('year') if request.GET.get('year') else datetime.now().year
        selected_month = request.GET.get('month') if request.GET.get('month') else None
        if selected_month:
            days = [i for i in range(1,monthrange(int(selected_year), int(selected_month))[1]+1)]
            data['data'] = [day for day in days]
            data['Sellers_count']= [User.objects.filter(role_id=SELLER, created_on__month = selected_month,created_on__day = day,created_on__year = selected_year).count() for day in days]
            data['active_Sellers_count']=  [User.objects.filter(role_id=SELLER,created_on__month = selected_month,created_on__day = day,created_on__year = selected_year,status=ACTIVE).count() for day in days  ]
            data['inactive_Sellers_count']= [User.objects.filter(role_id=SELLER,created_on__month = selected_month,created_on__day = day,created_on__year = selected_year,status=INACTIVE).count() for day in days  ]
            data['deleted_Sellers_count']= [User.objects.filter(role_id=SELLER,created_on__month = selected_month,created_on__day = day,created_on__year = selected_year,status=DELETED).count() for day in days  ]
            data['month_name']=calendar.month_name[int(selected_month)]   
        else:
            data['data'] = ['Jan', 'Feb', 'March', 'April', 'May', 'June', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            data['Sellers_count']= [User.objects.filter(role_id=SELLER,created_on__month = i,created_on__year = selected_year,).count() for i in range(1,13)]
            data['active_Sellers_count'] = [User.objects.filter(role_id=SELLER,created_on__month=i,created_on__year=selected_year,status=ACTIVE).count() for i in range(1,13)  ]
            data['inactive_Sellers_count'] = [User.objects.filter(role_id=SELLER,created_on__month=i,created_on__year=selected_year,status=INACTIVE).count() for i in range(1,13)  ]
            data['deleted_Sellers_count'] = [User.objects.filter(role_id=SELLER,created_on__month=i,created_on__year=selected_year,status=DELETED).count() for i in range(1,13)  ]

        chart = {
            'title': {
                'text': ''
            },
            'xAxis': { 
                'categories': data['data'],
                'lineWidth': 0,
            },
            'yAxis': {
                'min': 0,
                'max': 5 if max(data['Sellers_count']) <= 5 else max(data['Sellers_count'])+10,
                'allowDecimals': False,
                'align': 'left',
                'x': 10,
                'lineWidth': 0,
                'gridLineWidth': 1,
                'title': {
                    'enabled': False,
                },
            },    
            'colors': ["#407BFF","#229b09","#ffc107","#e80303"],
            'series': [
                {
                    'type': 'spline',
                    'name': 'Sellers Registered',
                    'data': data['Sellers_count'],
                }, 
                {
                    'type': 'column',
                    'name': 'Active Sellers',
                    'data': data['active_Sellers_count'],
                }, 
                {
                    'type': 'column',
                    'name': 'Inactive Sellers',
                    'data': data['inactive_Sellers_count'],
                }, 
                {
                    'type': 'column',
                    'name': 'Deleted Sellers',
                    'data': data['deleted_Sellers_count'],
                }, 
              
            ],
            'accessibility': {
                'enabled': False
            },
        }

        data['users']=chart   
        data['selected_year']=selected_year
        return JsonResponse(data)
    

app/templates/users/sellers/sellers.html
{% include "admin-includes/header.html" %}
{% load static %}
{% load extras %}
<div class="page-wrapper">
    <div class="content">
        <div class="page-header">
            <div class="page-title">
                <h4>Sellers</h4>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
						<li class="breadcrumb-item"><a class="white-text" href="/">Dashboard</a></li>
                        <li class="breadcrumb-item"><a class="white-text" href="{% url 'sellers:seller_list' %}">Sellers</a>
                        </li>
                    </ol>
                </nav>
            </div>
			<div class="page-btn d-flex flex-wrap">
				{% if users %}
                <form action="{% url 'users:download_customer_reports' %}?role_id=3" method="POST">
					{% csrf_token %} 			
					<input type ="hidden" class ="timezone" name ="timezone">
					<div><button type="submit" class="btn btn-primary sharp me-2"><i class="fas fa-download me-2"></i>Export Csv</button></div>
				</form> 
				{% endif %}
                {% comment %} <a class="btn btn-primary" href="{% url 'users:add_user' %}"><i class="fas fa-plus me-2"></i> Buyer</a> {% endcomment %}
            </div>
        </div>
		<!-- cards -->
		<div class="row state-overview">
            <div class="col-xl-3 col-lg-4 col-sm-6 col-12">
                <a href="?" style="color: inherit;" class="d-flex">
                    <div class="dash-count das4">
                        <div class="dash-counts">
                            <h5>Total Sellers</h5>
                            <h4>{{'total_user'|sellers_count}}</h4>
                        </div>
                        <div class="dash-imgs">
                            <span><i class="fad fa-users"></i></span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xl-3 col-lg-4 col-sm-6 col-12">
                <a href="?status=1" style="color: inherit;" class="d-flex">
                    <div class="dash-count das5">
                        <div class="dash-counts">
                            <h5>Active Sellers</h5>
                            <h4>{{'active_user'|sellers_count}}</h4>
                        </div>
                        <div class="dash-imgs">
                            <span><i class="fas fa-badge-check"></i></span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xl-3 col-lg-4 col-sm-6 col-12">
                <a href="?status=2" style="color: inherit;" class="d-flex">
                    <div class="dash-count das6">
                        <div class="dash-counts">
                            <h5>Inactive Sellers</h5>
                            <h4>{{'inactive_user'|sellers_count}}</h4>
                        </div>
                        <div class="dash-imgs">
                            <span><i class="fas fa-times-circle"></i></span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xl-3 col-lg-4 col-sm-6 col-12">
                <a href="?status=3" style="color: inherit;" class="d-flex">
                    <div class="dash-count das7">
                        <div class="dash-counts">
                            <h5>Deleted Sellers</h5>
                            <h4>{{'deleted_user'|sellers_count}}</h4>
                        </div>
                        <div class="dash-imgs">
                            <span><i class="fas fa-user-minus"></i></span>
                        </div>
                    </div>
                </a>
            </div>
        </div>
		<!-- cards end -->

		<div class="card">
			<div class="col-xl-12 col-lg-12">
				<div class="card flex-fill">
					<div class="card-header pb-0 d-md-flex justify-content-between align-items-center">
						<h5 class="card-title">Sellers Registered in <span id="r_selected_year"></span>{% if selected_month %}(<span id="r_selected_month"></span>){% endif %}</h5>
						<div class="graph-sets mt-md-0 mt-2">
							<div class="dropdown d-flex">
                                <input type="hidden" id="Url1" data-url="{% url 'sellers:seller_graph' %}" />
								<select class="graph-dropdown me-2" name="r_months" id="r_months" onchange="GetRentersGraphData(this.value)">
									<option value="">Select</option>
									<option value="1">January</option>
									<option value="2">February</option>
									<option value="3">March</option>
									<option value="4">April</option>
									<option value="5">May</option>
									<option value="6">June</option>
									<option value="7">July</option>
									<option value="8">August</option>
									<option value="9">September</option>
									<option value="10">October</option>
									<option value="11">November</option>
									<option value="12">December</option>
								</select>
								<select class="graph-dropdown" name="r_years" id="r_years" onchange="GetRentersGraphData(this.value)"></select>
							</div>
						</div>
					</div>
					<div class="card-body">
						<div class="row">
							<div class="col-12">
								<div id="chart-container1"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
        <div class="card mt-2">
            <div class="card-body" id="card_body_div">
                <div class="dataview">
                    <form onsubmit="Loader()" action="" method="GET">
						<div class="table-responsive">
							<table class="table datatable">
								<thead>
									<tr>
										<th>Full Name</th>
										<th>Email</th>
										<th>Mobile Number</th>
										<th>Created on From</th>
										<th>Created on To</th>
										<th>Status </th>
										<th>Actions</th>
									</tr>
								</thead>
								<thead>
									<tr class="search-row">
										<td><input type="text"  value="{{full_name}}" class="form-control" name="full_name" maxlength="20"></td>
										<td><input type="text" value="{{email}}" class="form-control" name="email" maxlength="40"></td>
										<td><input type="text" value="{{mobile_no}}" onkeypress="return /[0-9]/i.test(event.key)" onchange="this.form.submit()" class="form-control" name="mobile_no" maxlength="20"></td>
										<td><input type="date" onkeydown="return false" value="{{created_on_from}}" class="position-relative form-control" name="created_on_from" onchange="this.form.submit()"></td>
										<td><input type="date" onkeydown="return false" value="{{created_on_to}}" class="position-relative form-control" name="created_on_to" onchange="this.form.submit()"></td>
										<td>
											<select class="form-control" name="status" onchange="this.form.submit()">
												<option  value=""></option>
												<option {% if status == '1' %} selected {% endif %} value="1">ACTIVE</option>
												<option {% if status == '2' %} selected {% endif %} value="2">INACTIVE</option>
												<option {% if status == '3' %} selected {% endif %} value="3">DELETED</option>
											</select>
										</td>
										<td><button type="submit" onclick="refresh()"  class="btn btn-primary">Search</button></td>
									</tr>
								</thead>
								<tbody>
									{% if users %}
										{% for user in users %}
										<tr>
											<td>
												<div class="d-flex align-items-center display-images">
													{% if user.profile_pic %}
													<a href="{{user.profile_pic.url}}" data-fancybox>
														<img src="{{user.profile_pic.url}}" class="rounded-lg me-2" width="24" alt="">
													</a>
													{% else %}
													<a href="{% static 'admin-assets/images/dp.png' %}" data-fancybox>
														<img src="{% static 'admin-assets/images/dp.png' %}"
														class="rounded-lg me-2" width="24" alt="">
													</a>
													{% endif %}
													{% if user.full_name %}
													<span class="w-space-no">{{ user.full_name }}</span>
													{% else %}
													<span class="w-space-no">-</span>
													{% endif %}
												</div>
											</td>
											<td class='clickable-row' data-href="{% url 'users:view_user' user.id %}">
												{% if user.email %}{{ user.email }}{% else %}-{% endif %}
											</td>
											<td class='clickable-row' data-href="{% url 'users:view_user' user.id %}">
												{% if user.mobile_no %}{% if user.country_code %}{{user.country_code}}{% endif %}{{ user.mobile_no }}{% else %}-{% endif %}
											</td>
											<td class='clickable-row' data-href="{% url 'users:view_user' user.id %}">
												<span class="w-space-no">
												<script>
													var date = ConvertDateTime("{{ user.created_on|date:'Y-m-d' }}", "{{ user.created_on|time:'H:i' }}");
													document.write(date);
												</script>
												</span>
											</td>
											<td class='clickable-row' data-href="{% url 'users:view_user' user.id %}">

												<span class="w-space-no">
													{% if created_on_to %}
													{% date_format created_on_to as date_format  %}
														<script>
															var date = ConvertDateTime1("{{ date_format|date:'Y-m-d' }}", "{{ date_format|time:'H:i' }}");
															document.write(date);
														</script>
													{% else %}
												<script>
													var date = ConvertDateTime("{{1|today_date|date:'Y-m-d' }}", "{{1| today_date|time:'H:i' }}");
													document.write(date);
												</script>
												{% endif %}
												</span>
											</td>
											<td class='clickable-row' data-href="{% url 'users:view_user' user.id %}">
												{% if user.status == 1 %}
												<span class="badge bg-success">ACTIVE</span>
												{% elif user.status == 2 %}
												<span class="badge bg-warning">INACTIVE</span>
												{% else %}
												<span class="badge bg-danger">DELETED</span>
												{% endif %}
											</td>
											<td>
												<div class="d-flex">
													<a title="View Details" href="{% url 'users:view_user' user.id %}" class="btn btn-success shadow btn-xs sharp me-1"><i class="fa fa-eye"></i></a>
													{% comment %} <a class="btn btn-info shadow btn-xs sharp me-1" href="{% url 'users:edit_user' user.id %}"><i class="fa fa-edit"></i></a> {% endcomment %}
												</div>
											</td>
										</tr>
										{% endfor %}
									{% endif %}
								</tbody>
							</table>
						</div>
					</form>
                    {% if users.has_other_pages %}
						<nav aria-label="Page navigation">
							<ul class="pagination">
								{% if users.has_previous %}
									<li class="page-item">
										<a class="page-link" href="?{% url_replace request 'page' users.previous_page_number %}">&laquo;</a>                                          
									</li>
								{% else %}
									<li class="page-item disabled">
										<span class="page-link">&laquo;</span>
									</li>
								{% endif %}
								{% for i in users.paginator.page_range %}
									{% if users.number == i %}
										<li class="page-item active">
											<span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
										</li>
									{% elif i > users.number|add:'-5' and i < users.number|add:'5' %}
										<li class="page-item">
											<a class="page-link" href="?{% url_replace request 'page' i %}">{{ i }}</a>
										</li>
									{% endif %}
								{% endfor %}
								{% if users.has_next %}
									<li class="page-item">
										<a class="page-link" href="?{% url_replace request 'page' users.next_page_number %}">&raquo;</a>
									</li>
								{% else %}
									<li class="page-item disabled">
										<span class="page-link">&raquo;</span>
									</li>
								{% endif %}
							</ul>
						</nav>
					{% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% include "admin-includes/footer.html" %}
<script src="{% static 'admin-assets/js/customized-js/graph.js' %}"></script>

<script>
// redirects on same div location after refresh
$(document).ready(function() {
    if("{{scroll_required}}" == "True"){
        $('html, body').animate({
            scrollTop: ($("#card_body_div").offset().top + 170)
        }, 100);
    }
});
</script>