app/api/urls.py
import os
import environ
from django.contrib import admin
from django.urls import re_path
from .views_authentication import *
env = environ.Env()
environ.Env.read_env()

admin.autodiscover()
app_name = 'api'


urlpatterns = [
    ## Authentication
    # re_path(r'^user-signup-api/$',UserSignupView.as_view(),name="user_signup_api"),
    re_path(r'^user-login-api/$',UserLoginView.as_view(),name="user_login_api"),
    re_path(r'^check-user-api/$', UserCheckView.as_view(), name='check_user_api'),
    re_path(r'^delete-account-api/$',DeleteAccount.as_view(),name="delete_account_api"),
    re_path(r'^deactivate-account-api/$',DeactivateAccount.as_view(),name="deactivate_account_api"),
    re_path(r'^logout-api/$', LogoutView.as_view(), name='logout_api'),

    re_path(r'^verify-otp-api/$',VerifyOTP.as_view(),name="verify_otp_api"),
    re_path(r'^resend-otp-api/$',ResendOTP.as_view(),name="resend_otp_api"),

    re_path(r'^check-user-mail/$',CheckUserEmail.as_view(),name="check_user_mail"),
    
    re_path(r'^forgot-password-api/$',ForgotPassword.as_view(),name="forgot_password_api"),
    re_path(r'^forgot-password-resend-otp/$',ForgotPasswordResendOTP.as_view(),name="forgot_password_resend_otp_api"),
    
    ##Security Management
    re_path(r'^change-password-api/$',ChangePassword.as_view(),name="change_password_api"),
    re_path(r'^reset-password/$',ResetPasswordView.as_view(),name="reset_password_api"),

    ## Profile Management
    re_path(r'^profile-details-api/$',UserProfileDetails.as_view(),name="user_profile_details_api"),
    re_path(r'^update-profile-api/$',UpdateProfileDetails.as_view(),name="update_profile_api"),
    re_path(r'^update-mobile-number-api/$',UpdateMobileNumberView.as_view(),name="update_mobile_number_api"),
    re_path(r'^verify-mobile-number-api/$',VerifyMobileNumberView.as_view(),name="verify_mobile_number_api"),

    ## Static Pages
    re_path(r'^static-pages-api/$',StaticPages.as_view(),name="static_pages_api"),

    ## Faq Management
    re_path(r'^faq-list-api/$',FaqList.as_view(),name="faq_list_api"),
    
    ## Contact Us Management
    re_path(r'^contact-us-api/$',ContactUsView.as_view(),name="contact_us_api"),

    ## Notification Management
    re_path(r'^update-notification-settings-api/$',UpdateNotificationSettings.as_view(),name="update_notification_settings_api"),
    re_path(r'^notifications-list-api/$',NotificationsList.as_view(),name="notifications_list_api"),
    re_path(r'^clear-all-notifications-api/$',ClearAllNotifications.as_view(),name="clear_notifications_api"),
    re_path(r'^delete-notification-api/$',DeleteNotification.as_view(),name="delete_notification_api"),
    re_path(r'^mark-read-notification-api/$',MarkReadNotification.as_view(),name="mark_read_notification_api"),
    
]

app/credentials/urls.py
from .views import *
from django.contrib import admin
from django.urls import re_path
admin.autodiscover()
app_name = 'credentials'

urlpatterns = [
    ## SMTP Settings
    re_path(r'^smtp-list/$',SMTPListView.as_view(),name="smtp_list"),
    re_path(r'^add-smtp/$',AddSMTPView.as_view(),name="add_smtp"),
    re_path(r'^delete-smtp/(?P<id>[-\w]+)/$', DeleteSMTP.as_view(), name='delete_smtp'),
    re_path(r'^view-smtp/(?P<id>[-\w]+)/$', ViewSMTP.as_view(), name='view_smtp'),
    re_path(r'^edit-smtp/(?P<id>[-\w]+)/$', EditSMTP.as_view(), name='edit_smtp'),
    re_path(r'^active-deactive-smtp/(?P<id>[-\w]+)/$', ActivateDeActiveSMTP.as_view(), name='active_deactive_smtp'),

    ##Firebase Credentials
    re_path(r'^firebase-credentials-list/$',FirebaseCredentialsList.as_view(),name="firebase_credentials_list"),
    re_path(r'^add-firebase-credentials/$',AddFirebaseCredentials.as_view(),name="add_firebase_credentials"),
    re_path(r'^view-firebase-credentials/(?P<id>[-\w]+)/$',ViewFirebaseCredentials.as_view(),name="view_firebase_credentials"),
    re_path(r'^change-firebase-status/(?P<id>[-\w]+)/$',ActivateFirebaseStatus.as_view(),name="change_firebase_status"),
    re_path(r'^update-firebase-credentials/(?P<id>[-\w]+)/$',UpdateFirebaseCredential.as_view(),name="update_firebase_credentials"),
    re_path(r'^delete-firebase-credentials/(?P<id>[-\w]+)/$',DeleteFirebase.as_view(),name="delete_firebase_credentials"),

    ## Stripe Settings
    re_path(r'^stripe-list/$',StripeListView.as_view(),name="stripe_list"),
    re_path(r'^add-stripe/$',AddStripeKeyView.as_view(),name="add_stripe"),
    re_path(r'^delete-stripe/(?P<id>[-\w]+)/$', DeleteStripeKey.as_view(), name='delete_stripe'),
    re_path(r'^view-stripe/(?P<id>[-\w]+)/$', ViewStripeKey.as_view(), name='view_stripe'),
    re_path(r'^edit-stripe/(?P<id>[-\w]+)/$', EditStripeKey.as_view(), name='edit_stripe'),
    re_path(r'^active-deactive-stripe/(?P<id>[-\w]+)/$', ActivateDeActiveStripeKey.as_view(), name='active_deactive_stripe'),
]

app/project/urls.py
from django.contrib import admin
from frontend.views import *
from accounts.views import  *
from django.conf import settings
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import  AdminLoginView
from django.views.static import serve

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from drf_yasg.generators import OpenAPISchemaGenerator


class SchemaGenerator(OpenAPISchemaGenerator):
    def get_schema(self, request=None, public=False):
        schema = super(SchemaGenerator, self).get_schema(request, public)
        schema.basePath = os.path.join(schema.basePath, '')
        schema.schemes = ["http", "https"]
        return schema


schema_view = get_schema_view(
    openapi.Info(
        title = "<ProjectName>'s API's",
        description = "API documentation for <ProjectName> Project",
        default_version = "1.0.0",
        terms_of_service = env('BASE_URL')+"/terms-and-conditions/",
        contact = openapi.Contact(email=""),
        license = openapi.License(name="<ProjectName>"),
    ),
    public = True,
    permission_classes = (permissions.AllowAny,),
    generator_class = SchemaGenerator
)



urlpatterns = [
    re_path(r'^admin/login/', AdminLoginView.as_view()),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'',include('frontend.urls')),

    ## Documentation Swagger
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^documentation/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    re_path(r'^accounts/', include('accounts.urls',)),
    re_path(r'^api/', include('api.urls',)),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^logger/', include('logger.urls',)),
    re_path(r'^users/', include('users.urls',)),
    re_path(r'^static-pages/', include('static_pages.urls',)),
    re_path(r'^backup/', include('backup.urls',)),
    re_path(r'^contact-us/', include('contact_us.urls',)),
    re_path(r'^credentials/', include('credentials.urls',)),
    re_path(r'^sellers/', include('sellers.urls',)),
    re_path(r'^products/', include('products.urls',)),
    # re_path(r'^chat/', include('chat.urls',)),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.handler404'
handler500 = 'frontend.views.handler500'
handler403 = 'frontend.views.handler403'
handler400 = 'frontend.views.handler400'

app/templates/stripe/add-stripe.html
{% include 'admin-includes/header.html' %}
{% load static %}
<div class="page-wrapper">
    <div class="content">
        <div class="page-header">
            <div class="page-title">
                <h4>Stripe Key Settings</h4>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="white-text" href="/">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'credentials:stripe_list' %}"
                                class="white-text">Stripe Setting</a></li>
                        <li class="breadcrumb-item active">Add Stripe Key</li>
                    </ol>
                </nav>
            </div>
            <div class="page-btn d-flex flex-wrap">
                <a class="btn btn-secondary" href="{% url 'credentials:stripe_list' %}"><i class="fa fa-angle-left me-1"></i> Back</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <form onsubmit="Loader(this.id)" id="add-key" action="{% url 'credentials:add_stripe' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-12 mx-auto">
                            <div class="form-group required-field">
                                <label class="form-label">Test Key</label>
                                <input type="text" placeholder="Enter Stripe Test Key" name="test_secretkey" class="form-control" maxlength="254" value={{test_secretkey}}>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-12 mx-auto">
                            <div class="form-group required-field">
                                <label class="form-label">Publishable Key</label>
                                <input type="text" placeholder="Enter Stripe Publishable Key" name="test_publishkey" class="form-control" maxlength="254" value={{test_publishkey}}>
                            </div>
                        </div>
                        <div class="col-lg-12 text-end">
                            <button type="submit" class="btn btn-primary me-2">Save</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% include 'admin-includes/footer.html' %}
<script type="text/javascript">
    $("#add-key").validate({
        rules: {
            test_secretkey: {
                required: true,
                normalizer: function (value) {
                    return $.trim(value);
                }
            },
            test_publishkey: {
                required: true,
                normalizer: function (value) {
                    return $.trim(value);
                },
            },
        },
        messages: {
            test_secretkey: {
                required: "Please enter secret key"
            },
            test_publishkey: {
                required: "Please enter publish key",
            },
        }
    });  
</script>

app/templates/stripe/edit-stripe.html
{% include 'admin-includes/header.html' %}
{% load static %}
<div class="page-wrapper">
    <div class="content">
        <div class="page-header">
            <div class="page-title">
                <h4>Stripe Key Settings</h4>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="white-text" href="/">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'credentials:stripe_list' %}" class="white-text">Stripe Setting</a></li>
                        <li class="breadcrumb-item active">Edit Stripe Key</li>
                    </ol>
                </nav>
            </div>
            <div class="page-btn d-flex flex-wrap">
                <a class="btn btn-secondary" href="{% url 'credentials:stripe_list' %}"><i class="fa fa-angle-left me-1"></i> Back</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <form onsubmit="Loader(this.id)" id="edit-key" action="{% url 'credentials:edit_stripe' stripe_key.id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-12 mx-auto">
                            <div class="form-group required-field">
                                <label class="form-label">Test Key</label>
                                <input type="text" placeholder="Enter Stripe Test Key" name="test_secretkey" value="{{stripe_key.test_secretkey}}" class="form-control" maxlength="254" value={{test_secretkey}}>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-12 mx-auto">
                            <div class="form-group required-field">
                                <label class="form-label">Publishable Key</label>
                                <input type="text" placeholder="Enter Stripe Publishable Key" name="test_publishkey" value="{{stripe_key.test_publishkey}}" class="form-control" maxlength="254" value={{test_publishkey}}>
                            </div>
                        </div>
                        <div class="col-lg-12 text-end">
                            <button type="submit" class="btn btn-primary me-2">Save</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% include 'admin-includes/footer.html' %}
<script type="text/javascript"> 
    $("#edit-key").validate({
        rules: {
            test_secretkey: {
                required: true,
                normalizer: function (value) {
                    return $.trim(value);
                }
            },
            test_publishkey: {
                required: true,
                normalizer: function (value) {
                    return $.trim(value);
                },
            },
        },
        messages: {
            test_secretkey: {
                required: "Please enter secret key"
            },
            test_publishkey: {
                required: "Please enter publish key",
            },
        }
    });     
</script>

app/templates/stripe/stripe-list.html
{% include 'admin-includes/header.html' %}
{% load static %}{% load extras %}
<div class="page-wrapper">
    <div class="content">
        <div class="page-header">
            <div class="page-title">
                <h4>Stripe Key Settings</h4>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="white-text" href="/">Dashboard</a></li>
                        <li class="breadcrumb-item"><a class="white-text" href="{% url 'credentials:stripe_list' %}">Stripe Key Settings</a> </li>
                    </ol>
                </nav>
            </div>
            <div class="page-btn d-flex flex-wrap">
                <a class="btn btn-primary theme-btn-2" href="{% url 'credentials:add_stripe' %}"><i class="fas fa-plus ms-1"></i> Stripe Key</a>
            </div>
        </div>
        {% if stripe_keys %}
        <p><b>* Please ensure that at least one key is active at a time.</b></p>
        {% endif %}
        <div class="card">
            <div class="card-body">
                <div class="dataview">
                    <form onsubmit="Loader()" action="{% url 'credentials:stripe_list' %}" method="GET">
                        <div class="table-responsive ">
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>Test Key</th>
                                        <th>Publishable Key</th>
                                        <th>Is Active</th>
                                        <th>Created on</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <thead>
                                    <tr class="search-row">
                                        <td>
                                            <input type="text" value="{{test_secretkey}}" class="form-control" name="test_secretkey" maxlength="20">
                                        </td>
                                        <td>
                                            <input type="text" value="{{test_publishkey}}" class="form-control" name="test_publishkey" maxlength="20">
                                        </td>
                                        <td>
                                            <select class="form-control" name="is_active" onchange="this.form.submit()">
                                                <option value=""></option>
                                                <option {% if is_active == '1' %} selected {% endif %} value="1">Active
                                                </option>
                                                <option {% if is_active == '0' %} selected {% endif %} value="0">Inactive
                                                </option>
                                            </select>
                                        </td>
                                        <td>
                                            <input type="date" onkeydown="return false" value="{{created_on}}" class="position-relative form-control" onchange="this.form.submit()" name="created_on">
                                        </td>
                                        <td>
                                            <button type="submit" class="btn btn-primary">Search</button>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for key in stripe_keys %}
                                    <tr>
                                        <td class='clickable-row' data-href="{% url 'credentials:view_stripe' key.id %}">
                                            {% if key.test_secretkey  %}{{key.test_secretkey| truncatechars:50}}{% else %}-{% endif %}
                                        </td>
                                        <td class='clickable-row' data-href="{% url 'credentials:view_stripe' key.id %}">
                                            {% if key.test_publishkey  %}{{key.test_publishkey| truncatechars:50}}{% else %}-{% endif %}
                                        </td>
                                        <td>
                                            {% if key.is_active == True %}
                                                <span class="badge bg-success active_deactive" message="Are you sure you want to deactivate?" action='DeActivate' href="{% url 'credentials:active_deactive_stripe' key.id %}">Active</span>
                                            {% elif key.is_active == False %}
                                                <span class="badge bg-warning active_deactive" message="Are you sure you want to activate?" action='Activate' href="{% url 'credentials:active_deactive_stripe' key.id %}" >InActive</span>
                                            {% endif %}
                                        </td>

                                        {% if  key.created_on %}
                                        <td class='clickable-row'
                                            data-href="{% url 'credentials:view_stripe' key.id %}">
                                            <script>
                                                var d = ConvertDateTime("{{ key.created_on|date:'Y-m-d' }}", "{{ key.created_on|time:'H:i' }}");
                                                document.write(d);
                                            </script>
                                        </td>
                                        {% endif %}
                                        <td>
                                            <div class="d-flex">
                                                <a href="{% url 'credentials:edit_stripe' key.id %}" class="btn btn-info shadow btn-xs sharp me-1"><i class="fa fa-edit"></i></a>
                                                <a href="{% url 'credentials:view_stripe' key.id %}" class="btn btn-success shadow btn-xs sharp me-1"><i class="fa fa-eye"></i></a>
                                                <a style="margin-right:5px" href="{% url 'credentials:delete_stripe' key.id %}" message="Are you sure you want to delete this key?" class="btn btn-danger shadow btn-xs sharp action_confirm"><i class="fa fa-trash"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </form>

                    {% if stripe_keys.has_other_pages %}
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            {% if stripe_keys.has_previous %}
                            <li class="page-item">
                                <a class="page-link"
                                    href="?{% url_replace request 'page' stripe_keys.previous_page_number %}">&laquo;</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">&laquo;</span>
                            </li>
                            {% endif %}
                            {% for i in stripe_keys.paginator.page_range %}
                            {% if stripe_keys.number == i %}
                            <li class="page-item active">
                                <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                            </li>
                            {% elif i > stripe_keys.number|add:'-5' and i < stripe_keys.number|add:'5' %} <li class="page-item">
                                <a class="page-link" href="?{% url_replace request 'page' i %}">{{ i }}</a>
                                </li>
                                {% endif %}
                                {% endfor %}
                                {% if stripe_keys.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?{% url_replace request 'page' stripe_keys.next_page_number %}">&raquo;</a>
                                </li>
                                {% else %}
                                <li class="page-item disabled">
                                    <span class="page-link">&raquo;</span>
                                </li>
                                {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'admin-includes/footer.html' %}

<script>
    function GetPageId(id) {
        $('#stripe_id1').val(id);
        $('#stripe_id2').val(id);
    }
</script>

app/templates/stripe/view-stripe.html
{% include "admin-includes/header.html" %}{% load static %}
<div class="page-wrapper">
    <div class="content">
        <div class="page-header">
            <div class="page-title">
                <h4>Stripe Key Settings</h4>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"><a class="white-text" href="/">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'credentials:stripe_list' %}" class="white-text">Stripe Key Setting</a></li>
                        <li class="breadcrumb-item active">View Stripe Key</li>
                    </ol>
                </nav>
            </div>
            <div class="page-btn d-flex flex-wrap">


                <a href="{% url 'credentials:edit_stripe' stripe_key.id %}" class="btn btn-info shadow btn-xs sharp me-1"><i class="fa fa-edit"></i></a>
                <a style="margin-right:5px" href="{% url 'credentials:view_stripe' stripe_key.id %}" message="Are you sure you want to delete this key?" class="btn btn-danger shadow btn-xs sharp action_confirm" ><i class="fa fa-trash"></i></a>
                <a class="btn btn-secondary" href="{% url 'credentials:stripe_list' %}"><i class="fa fa-angle-left me-1"></i> Back</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="productdetails">
                            <ul class="product-bar">
                                <li>
                                    <h4>Test Key</h4>
                                    <h6><b>{{stripe_key.test_secretkey}}</b></h6>
                                </li>
                                <li>
                                    <h4>Publishable Key</h4>
                                    <h6><b>{{stripe_key.test_publishkey}}</b></h6>
                                </li>
                                <li>
                                    <h4>Is Active </h4> 
                                    <h6>
                                    {% if stripe_key.is_active == True %}
                                        <span style='cursor:pointer'  class="badge bg-success active_deactive" message="Are you sure you want to deactivate?" action='DeActivate' href="{% url 'credentials:active_deactive_stripe' stripe_key.id %}">Active</span>
                                    {% else %}
                                        <span style='cursor:pointer'  class="badge bg-warning active_deactive" message="Are you sure you want to activate?" action='Activate' href="{% url 'credentials:active_deactive_stripe' stripe_key.id %}" >InActive</span>
                                    {% endif %}
                                    </h6>
                                </li>
                                {% if  stripe_key.created_on %}
                                <li>
                                    <h4>Created On </h4>
                                    <h6>
                                        <script>
                                            var date = ConvertDateTime("{{ stripe_key.created_on|date:'Y-m-d' }}", "{{ stripe_key.created_on|time:'H:i' }}");
                                            document.write(date);
                                        </script>
                                    </h6>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="btn-list border-0 d-flex justify-content-end align-items-center mt-4">

            {% if stripe_key.is_active %}
                <a class="btn btn-danger me-2 active_deactive" message="Are you sure you want to deactivate?" action='DeActivate' href="{% url 'credentials:active_deactive_stripe' stripe_key.id %}">DEACTIVATE</a>
            {% else %}
                <a class="btn btn-primary me-2 active_deactive" message="Are you sure you want to activate?" action='Activate' href="{% url 'credentials:active_deactive_stripe' stripe_key.id %}" >ACTIVATE</a>
            {% endif %}

            </div>
                
        </div>
    </div>
</div>

{% include "admin-includes/footer.html" %}
<script>
    function GetPageId(id) {
        $('#stripe_id1').val(id);
        $('#stripe_id2').val(id);
    }
</script>